name: build-test-deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:

  build-integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - name: Install package dependencies
        run: npm install
      - name: Run Integration tests
        run: npm run test:unit

  run-ui-tests:
    needs: build-integration-tests
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - name: Install package dependencies
        run: npm install
      - name: Install test browsers
        run: npx playwright install
      - name: Run Integration tests
        run: npm run test:unit
      - name: Start application in background
        run: npm run start &
      - name: Run UI tests
        run: npm run test:unit

  deploy-app:
    needs: run-ui-tests
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy APP in production
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_KEY }}
          wait_deploy: true
